### ISSUE TITLE
PXE boot problem

### ISSUE THREAD

**Issue by forwardcomputers** [vmware/photon#1014]
Could someone please shed some light as to why this is not working for me.
** BTW. Where does the install log get saved to ?

Download the minimal 3.0 Revision 2 ISO from Github download page.
Extracted 'initrd.img' and 'vmlinuz' from the isolinux directory.

Using this iPXE configuration

```
initrd  http://abc/photon/initrd.img
boot    http://abc/photon/vmlinuz initrd=initrd.img repo=http://packages.vmware.com/photon/3.0/photon_release_3.0_x86_64 root=/dev/ram0 loglevel=3 ks=http://abc/photon/ks.json

```        
This kickstart

```
{
  "hostname": "photon",
  "password": {
    "crypted": false,
    "text": "changeme"
  },
  "disk": "/dev/nvme0n1",
  "packagelist_file": "packages_minimal.json",
  "network": {
    "type": "dhcp"
  },
  "install_linux_esx": false
}

```
Install finishes, but will not boot, gives 'error: not a regular file'

If use the ISO and append 'ks=http://abc/photon/ks.json' to the kernel line, all is well.

**Comment by YustasSwamp** [comment]
Let's debug "Install finishes, but will not boot, gives 'error: not a regular file'"

After reboot do you see grub menu with Photon logo?
If you press 'c' , can you get to grub shell?
Can you run 'ls' command there to look at /boot folder?

Attach screenshots if possible.
Thanks

**Comment by forwardcomputers** [comment]
After reboot, I do get the grub menu with the Photon logo.
Looks like it's missing some files!!!

![Screen Shot 2020-05-26 at 4 42 25 PM](https://user-images.githubusercontent.com/39178654/82948588-0955e880-9f70-11ea-96c6-d6013d57917a.png)

**Comment by forwardcomputers** [comment]
Attached is a copy of ttyS0

[vmware.txt](https://github.com/vmware/photon/files/4685000/vmware.txt)

**Comment by forwardcomputers** [comment]
This is from the ISO install

[vmware_iso.txt](https://github.com/vmware/photon/files/4685043/vmware_iso.txt)

**Comment by YustasSwamp** [comment]
No kernel was installed. System must have `linux` or `linux-esx` rpms installed.
From the console:
"No package linux-4.19.79 available"

The issue is: packages_minimal.json you use is looking for specific version of linux (4.19.79) which is not available in provided repo=.

Solutions: 
1. try to remove version from packages_minimal.json to have just packages names like: "linux"
2. change repo= pointing to smth else which will have all needed files (content of ISO?)
3. do not use 
```
"packagelist_file": "packages_minimal.json",
```
replace it with
```
     "packages": ["minimal",  "linux",  "initramfs" ],
```

3rd solution seems correct to me.
in addition use `repo=https://packages.vmware.com/photon/3.0/photon_updates_3.0_x86_64/x86_64/` to get recent bits.

**Comment by forwardcomputers** [comment]
Thank you @YustasSwamp , works perfectly with the replaced line.

**Comment by YustasSwamp** [comment]
Glad to hear it.
