### ISSUE TITLE
Unable to mount floppy on Photon 3

### ISSUE THREAD

**Issue by crdzialowy** [vmware/photon#1020]
Related issue and use case but for Photon3 using photon-3.0-a0f216d:
https://github.com/vmware/photon/issues/798#issuecomment-518391423

**Comment by dcasota** [comment]
The tool [Ventoy](https://www.ventoy.net/) seems to support the use case in the context of packer and automation to (usb) boot a vanilla Photon 3 ISO, and it decompress additional files to initramfs by a plugin injection [concept](https://www.ventoy.net/en/plugin_injection.html). It supports MBR and EFI, and might be useful in an alternative delivery plan.  Personally I might use it for some tasks Photon on Azure, see https://github.com/ventoy/Ventoy/issues/373. Customer support is really good. Simply give a try is not wrong. Of course mount .img on Photon is a choice n+1 though.

**Comment by YustasSwamp** [comment]
Added. Will be available in linux-4.19.138-2.ph3 and linux-esx-4.19.138-2.ph3

**Comment by kkeshavamurthy** [comment]
I started working on using CDROM instead of HTTP. packer mounts the ks/preseed dirs provided as an ISO image as a second cdrom. When the image is booted on the first cdrom with the OS ISO image is mounted and I was not able to figure out how to mount the second cdrom during boot. If anyone has ideas, it would be appreciated.

I swithed to floppy and was able to get it to work for Ubuntu 18.04 & 20.04 ISO images. Floppy driver support in photon-3 has been recently (Aug 2020) added but the latest ISO available does not have the right kernel version which supports it. @codenrhoden anyway we can get a new photon ISO?
https://github.com/vmware/photon/issues/1020

I have not tried RHEL but floppy should be supported on it.
