### ISSUE TITLE
systemd.network not setting static route

### ISSUE THREAD

**Issue by maichai** [vmware/photon#1058]
I would like for eth1 not to use the default route provided by DHCP and instead set a static route to all internal networks via gateway 10.20.30.1
I crafted the following file, but systemd does not set the static route.
(I moved the default file 99-... out of the way, but based on how systemd uses these files it should not be used anyway for eth1, if the 91-... file is used first)
What is wrong in the file or is systemd buggy?

`/etc/systemd/network/91-eth1-dhcp-route.network`
```
[Match]
Name=eth1

[Network]
DHCP=yes
IPv6AcceptRA=no

[DHCP]
UseRoutes=false
UseGateway=false

[Route]
Gateway=10.20.30.1
Destination=172.16.0.0/12
Protocol=static
```

**Comment by ssahani** [comment]
IP routing policy is required  see https://systemd.network/systemd.network.html#%5BRoutingPolicyRule%5D%20Section%20Options. you need to add two routes.  One for the subnet so that the IP address can find its gateway. Another for specifying the default gateway for that interface. Finally, we add policy route rules for that IP address that we want to use that table. This will not only ensure that the IP address we#re trying to communicate with on that one interface can respond properly, but it will also ensure that we don#t route information between subnets.
```
[Network]
DHCP=yes
IPv6AcceptRA=no

[DHCP]
UseRoutes=false
UseGateway=false

[Route]
Destination=172.16.0.0/12
Protocol=static
Table=10
 
[Route]
Gateway=10.20.30.1
Table=10
 
[RoutingPolicyRule]
Table=10
To=(interface Address/mask )172.16.0.0/12
 
[RoutingPolicyRule]
Table=10
From= (interface Address/mask )172.16.0.0/12
```

**Comment by maichai** [comment]
OK thanks, sounds interesting.
I solved it by adding `GatewayOnlink=true `to the `[Route]`entry.
Does this  come with any drawbacks?

**Comment by ssahani** [comment]
`GatewayOnLink=` when your interface is directly connected to the GW. Kernel skips if the gateway is attached to the local network

**Comment by ssahani** [comment]
Do you need any further help or we can close this

**Comment by ssahani** [comment]
Closing as no response
