### ISSUE TITLE
Creating a user using useradd produces configuration error about PASS_MAX_DAYS

### ISSUE THREAD

**Issue by jandrews65** [vmware/photon#1070]
Version 3.0 
![image](https://user-images.githubusercontent.com/24566171/99888895-1fefaa80-2c48-11eb-83a3-8942b2030d24.png)

When creating a normal user via useradd, the user account is created and put into the correct group but returns an error

"configuration error - cannot parse PASS_MAX_DAYS value: '99999PASS_MIN_DAYS    0'

![image](https://user-images.githubusercontent.com/24566171/99888852-b7083280-2c47-11eb-9a0a-0945777a19f5.png)

and chage -l for the account the following result

![image](https://user-images.githubusercontent.com/24566171/99888855-d56e2e00-2c47-11eb-8451-3ae02d6305c2.png)

I'm not sure this is correct as the usual way for an account to not expire was to set MAX_DAYS to 99999. Before this build, when an account was created it was given a MAX_DAYS of 365 days or so by default. Has this convention been changed?

Looks like a parsing issue.

**Comment by YustasSwamp** [comment]
It is known issue which was fixed 1 year ago:
https://github.com/vmware/photon/commit/9c0ffd2910a0b3978537c41bf5846ba22370b195

This bug was introduced in installer code of Photon 3.0 rev2, but was fixed in 3.0 rev2 update 1
And it is not present in newer versions (3.0 rev2 up 2, 3.0 rev3).
https://github.com/vmware/photon/wiki/Downloading-Photon-OS

**Comment by ssahani** [comment]
Closing this as fixed
