### ISSUE TITLE
Package for tdnf-automatic [package]

### ISSUE THREAD

**Issue by cocowalla** [vmware/photon#1102]
I'm building an appliance with Photon OS 3.0, and wanted to enable automatic tdnf updates - naturally I searched for a `tdnf-automatic` package, but I see it's only available for the Photon 4.0 Beta, not for Photon 3.0 😞 

Would it be possible to make `tdnf-automatic` available for Photon OS 3.0 too?

**Comment by dcasota** [comment]
On a vanilla full Photon OS 3.0 it helps first updating the repo URL, see https://github.com/vmware/photon/issues/1074.
```
cd /etc/yum.repos.d/
sed -i 's/dl.bintray.com\/vmware/packages.vmware.com\/photon\/$releasever/g' photon.repo photon-updates.repo photon-extras.repo 
```
After that ```tdnf distro-sync -y```and ```tdnf update -y``` will work fine.

There are different 3.0 appliance flavors for "Generic", "VMware hypervisor optimized", "AWS optimized", "Security hardened" and "Real Time" though. 

Have you had a look to https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/commands.html ? As long as there are no new metadata, ```tdnf upgrade --refresh -y```doesn't show anything new.
```
tdnf upgrade --refresh -y
Refreshing metadata for: 'VMware Photon Extras 3.0(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 3.0(x86_64) Updates'
Refreshing metadata for: 'VMware Photon Linux 3.0(x86_64)'
```

Afaik there is not upgrading_to_photon_os_4.0 recipe like in https://vmware.github.io/photon/assets/files/html/3.0/photon_installation/Upgrading_to_photon_os_3.0.html yet as Photon OS 4.0 still is in beta. 
Those backward (yum) alternative package management paths not to forget, in your words the so-called _tdnf-automatic_ package feature in Photon OS 4.0 since introduced in tdnf 3.0 beta to _periodically download package upgrades and apply them_  might be promising.

**Comment by cocowalla** [comment]
Oops, apologies, I think I confused things by mentioning an appliance, and should have been clearer 😄  I meant I'm building my own appliance from scratch, based on the Photon OS Minimal ISO.

I realise I could hack something myself, using a SystemD timer unit and tdnf commands, but would prefer an officially supported `tdnf-automatic` package, like already exists for Photon OS 4.0.

**Comment by oliverkurth** [comment]
Looks like we have it now in 3.0:
```
root [ / ]# tdnf search tdnf-automatic
Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64)'
Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64) Updates'
Refreshing metadata for: 'VMware Photon Extras 3.0 (x86_64)'
tdnf-automatic : tdnf - automated upgrades 134   100%
tdnf-automatic : tdnf - automated upgrades
```
