### ISSUE TITLE
Cannot make x84-64 ph4 ostree based ova 

### ISSUE THREAD

**Issue by zanefounty** [vmware/photon#1224]
It does seem that this option worked previously as per this commit
https://github.com/vmware/photon/commit/6934ddc90494e7bfdda5d6c12c50458de7e2c91b#diff-ca2d9208fd67b3ae82502f003fc8e4fe34df83b0ca1516d23c1e582df9580aef

When trying to build an ova using ostree both the custom and default repo

`support/image-builder/ova/config_ova.json
                "ostree": {
                    "default_repo": false,
                    "repo_url": http://localhost:8080/rpm-ostree/base/4.0/x86_64/repo,
                    "repo_ref": "photon/4.0/x86_64/minimal"
                 }`

The build process get stuck at this point
`['chroot', '/home/devops/workspaces/photon/stage/ova/photon-chroot/ostree/deploy/photon/deploy/7db8d3ee568fc11ffec4e2be62cff8d2677a22e64c1dca2fe18108da7b05cbd2.0/', 'bash', '-c', 'grub2-mkconfig -o /boot/grub2/grub.cfg;']`

I have tried both efi and bios and always seems to get stuck when using ostree (normal ova build works without issue) 
Using build server Ubuntu 18.04.5

**Comment by zanefounty** [comment]
Hi 
I was able to get the ostree ova to build in bios mode after https://github.com/vmware/photon/commit/2abf9c05d7fdbbecba0195748362e1aba3322e72 although did have issues with efi 

Also where is the docker file for vmware/photon-build:rpm-ostree-3.0 as I have not been able to find it?

**Comment by jaankit** [comment]
Hi @zanefounty ,

Thanks for reporting the issue. 
Yes, there was issue with grub2 which got fixed by https://github.com/vmware/photon/commit/2abf9c05d7fdbbecba0195748362e1aba3322e72 .

> although did have issues with efi

Could you please elaborate what issue you are facing with efi? 
I tried building "bootmode: efi" ova by making following changes:
```
diff --git a/support/image-builder/ova/config_ova.json b/support/image-builder/ova/config_ova.json
index 8912afa5c..d4a7b798b 100644
--- a/support/image-builder/ova/config_ova.json
+++ b/support/image-builder/ova/config_ova.json
@@ -1,6 +1,6 @@
 {
     "installer": {
-        "bootmode":"dualboot",
+        "bootmode":"efi",
         "hostname": "photon-machine",
         "packagelist_file": "packages_ova.json",
         "password": {
@@ -9,7 +9,8 @@
             "text": "changeme"
         },
         "public_key": "",
-        "linux_flavor": "linux-esx"
+        "linux_flavor": "linux-esx",
+        "ostree": {"default_repo": true}
     },
     "image_type": "ova",
     "size": 16384, 
```
For me built ova works fine without any issue. **Please make sure bootmode is selected as efi and not bios when deploying the built ova.**
Also, you can switch to efi mode directly if ova is generated with "bootmode":"dualboot" by changing the bootmode before booting.
"dualboot" option support both bios as well as efi mode.

> Also where is the docker file for vmware/photon-build:rpm-ostree-3.0 as I have not been able to find it?

https://hub.docker.com/r/vmware/photon-build/tags?page=1&ordering=last_updated

Thanks,
Ankit

**Comment by zanefounty** [comment]
Regarding the photon-build:rpm-ostree-3.0 i am looking for the source  Dockerfile i am trying to work out how to build vmware/photon-build:rpm-ostree-3.0 rather than relying on the dockerhub hosted image and not all the details are stored on Dockerhub.
