### ISSUE TITLE
Please bump Photon 2.0, 3.0 and 4.0 at the same time

### ISSUE THREAD

**Issue by clickbg** [vmware/photon#1357]
### Describe the bug

Hi,

Currently PhotonOS version is being bumped only for 2.0 and 4.0 while 3.0 is left behind.
Example: https://github.com/docker-library/official-images/pull/13215/commits/125201ce8673ec3ca5fa408c58ea504deeffb81d

We use both 2.0 and 3.0 in our projects and the version inconsistency is causing issues.
Is it possible to release all 3 images at the same time like you do with 2.0 and 4.0?

Thanks!

### Reproduction steps

1. Go to https://github.com/docker-library/official-images/pull/13215/commits/125201ce8673ec3ca5fa408c58ea504deeffb81d
2. 2.0 and 4.0 are being bumped from 20220916 to 20220923 but 3.0 is left behind on 20220916

...

### Expected behavior

All Photon versions should be bumped at the same time in order to avoid downstream users having to upgrade multiple times.

**Comment by sshedi** [comment]
Request makes sense but I'm unaware of docker image release criteria, meaning there should be some change in the given time frame in order to do a new release. Need more info on this.

cc: @michellew-vmware @gpiyush-dev

**Comment by michellew-vmware** [comment]
Hi,

Thank you for being interested in using our Photon OS.

We haver contract with docker hub team and we only publish new images on every Friday since the load is too high for them if we publish docker images everyday on docker hub.

>All Photon versions should be bumped at the same time in order to avoid downstream users having to upgrade multiple times.
It is not true. The docker image of 2.0, 3.0 and 4.0 are published only when we publish rpms which are by-default installed on photon os docker images. 
For example, we only publish a new linux rpm on photon 4.0 this week, there will no new docker image published for 4.0 this week. 

Thanks,
Michelle

**Comment by YustasSwamp** [comment]
We bump all versions at the same time (on Fridays). If any given version didn't get any updates since last tag, we do not bump it.
