### ISSUE TITLE
Resolve OpenSSL HIGH vulnerabilities in pre-3.0.7

### ISSUE THREAD

**Issue by bajorgensen** [vmware/photon#1369]
### Describe the bug

OpenSSL project just released two HIGH severity vulnerabilities:

- X.509 Email Address 4-byte Buffer Overflow (CVE-2022-3602)
- X.509 Email Address Variable Length Buffer Overflow (CVE-2022-3786)

[https://www.openssl.org/news/secadv/20221101.txt](https://www.openssl.org/news/secadv/20221101.txt)

Currently shipping in Photon OS is 3.0.6

### Reproduction steps

1. tdnf upgrade
2. reboot
3. openssl version

![openssl](https://user-images.githubusercontent.com/23266424/199531625-b2f396de-b2be-45a2-8eb7-42b28706f0e7.PNG)

### Expected behavior

Expect Photon project to upgrade to non-vulnerable version.

**Comment by tapakund** [comment]
Mentioned security issue has been already fixed in Photon OS 4.0 : https://github.com/vmware/photon/commit/56000faf700ddf30b62a4f7dfb590c566b64ce90

Pls consume openssl-3.0.6-2.

root@photon-297cb6324575 [ ~ ]# tdnf list openssl --refresh
Refreshing metadata for: 'VMware Photon Linux 4.0 (x86_64)'
Refreshing metadata for: 'VMware Photon Extras 4.0 (x86_64)'
Refreshing metadata for: 'VMware Photon Linux 4.0 (x86_64) Updates'
openssl.x86_64                              3.0.6-1.ph4              @System
openssl.x86_64                              1.1.1i-2.ph4        photon-release
openssl.x86_64                              3.0.6-2.ph4         photon-updates
root@photon-297cb6324575 [ ~ ]#

**Comment by bajorgensen** [comment]
ok, so it is patched, but version and date of OpenSSL was not changed?

**Comment by tapakund** [comment]
We have  backported the fixes to 3.0.6 and released openssl-3.0.6-2 with these security patches.

**Comment by pcgeng** [comment]
@tapakund  In Photon OS 4.0 Rev 1, you team did the same patches for 3.0.6 and released openssl-3.0.6-2, right?
![image](https://user-images.githubusercontent.com/13600428/199664518-0c7889a5-154e-4f29-90e0-fd791dac18a6.png)

**Comment by sshedi** [comment]
@pcgeng yes, `openssl-3.0.6-2` contains fix for `CVE-2022-3602` https://github.com/vmware/photon/commit/56000faf700ddf30b62a4f7dfb590c566b64ce90

And we updated `openssl` to `3.0.7` here https://github.com/vmware/photon/commit/736c9c514ca77cc018c881bc9f5ea90d84577b4c & it contains fix for `CVE-2022-3602 & CVE-2022-3786`

**Comment by pcgeng** [comment]
Thank you, so openssl-3.0.6-2 doesn't contain the fix for `CVE-2022-3786` and openssl will be upgraded to 3.0.7 to contain both fixes in Photon 4.0 Rev 1, right?

**Comment by sshedi** [comment]
Yes, that's correct.

**Comment by sshedi** [comment]
@pcgeng sorry for the confusion, I discussed about this with @tapakund and https://github.com/vmware/photon/commit/56000faf700ddf30b62a4f7dfb590c566b64ce90 fixes both `CVE-2022-3602 & CVE-2022-3786`

So, `openssl-3.0.6-2` contains fix for both the CVEs and we got confused with commit message, sorry about that.

**Comment by pcgeng** [comment]
@sshedi ok, I was just wondering why the announcement for security update 4.0 272 says both fixes are included: https://github.com/vmware/photon/wiki/Security-Update-4.0-272. It's clear to me now..

**Comment by bajorgensen** [comment]
Fixes was backported and released to OpenSSL 3.0.6
