### ISSUE TITLE
License Clarification for the Security Advisories

### ISSUE THREAD

**Issue by captn3m0** [vmware/photon#1384]
### Describe the bug

It's unclear what license the advisories are published under. The repository license is clear: https://github.com/vmware/photon/blob/master/LICENSE.md, but I'm unsure if this applies to the Advisories as well.

### Reproduction steps

NA

### Expected behavior

A LICENCE file should be present in the repository wiki perhaps? Or the LICENSE.md file should clarify the license for the wiki.

### Additional context

I'm working on integrating Photon OS Advisories with the OSV/GSD Databases, and I'm republishing the advisories in the OSV format here: https://github.com/captn3m0/photon-os-advisories

Picking up facts is straight-forward, but I'm unsure about the summary/details fields - for which I'd like to check the license before proceeding.

**Comment by tpepper** [comment]
I believe our public vuln info is intentionally shared for the sake of sharing, in which case a permissive license would make sense.  But surprising to me, VMware's VMSA's are similarly not marked clearly.  I'm chasing this down how to get this cleaned up and will report back here ASAP.

**Comment by tpepper** [comment]
Following up on this:

We likely will have an update on our copyright notice (and perhaps license?) on VMware-originated security advisories to be more expressly clear that sharing is intended.  But in reality that doesn't matter at all for most use cases:

https://www.cve.org/ as CNA is the effective upstream source for all of these advisories, even as advisories happen to be published in parallel in other places.  Copying from that CNA is expressly permitted as per https://www.cve.org/Legal/TermsOfUse.  Pulling from the CNA has the benefit of being a one-stop shop for all public vuln information, consolidating thousands of projects, vendors, and licenses down to a single location and license.

**Comment by captn3m0** [comment]
Checking to see if there's any clarity on the license.

**Comment by itaysk** [comment]
@tpepper is there any update to this? as you said, it's clear that CVEs are meant to be consumed by integrators but currently the license makes it impossible to do so.
redirecting consumers to another source isn't a good solution IMO since it's not clear if/how that source has legitimately obtained the data. also, there's importance to get the data from the vendor as opposed to the generic CVE, since the vendor's ID and severity are often different.

**Comment by pombredanne** [comment]
Can we have an official statement wrt. the license of the security advisory data
Specifically I have been refraining to add this data in VulnerableCode because no license means no license.
 
See https://github.com/nexB/vulnerablecode/issues/36

> - https://github.com/vmware/photon/wiki/Security-Advisories
> 
> See also:
> 
> - JSON https://packages.vmware.com/photon/photon_cve_metadata/
> - and Oval https://packages.vmware.com/photon/photon_oval_definitions/



@sshedi @rnjudge please help unlock this!

**Comment by chipchilders** [comment]
@tpepper thanks for flagging. Have raised internally and someone will reply once we determine what we want to do regarding this issue.

**Comment by pombredanne** [comment]
@chipchilders @tpepper Thanks! FWIW any license goes as long there is a license!
From our experience in collecting advisory data from many sources in https://github.com/nexB/vulnerablecode/tree/main/vulnerabilities/importers , the most common licenses are either CC-BY or CC-BY-SA, but there is a long tail of misc. permissive licenses. 

The highest common denominator across all data sources is CC-BY-SA which is a limited copyleft license and is therefore the license we have to use for the whole data set since we mix and merge the data.

**Comment by smaliakkal** [comment]
Updated License for this , https://github.com/vmware/photon/wiki/Security-Advisories

**Comment by tapakund** [comment]
Closing this issue as its completed.

**Comment by pombredanne** [comment]
@tapakund @smaliakkal and team ... Thank you ++ for following up on this! You guys are awesome. :bow:
