### ISSUE TITLE
ZFS on PH 5

### ISSUE THREAD

**Issue by gorec2005** [vmware/photon#1486]
Can't compile zfs ([zfs-2.1.12](https://github.com/openzfs/zfs/releases/download/zfs-2.1.12/zfs-2.1.12.tar.gz)) on PH 5:

autoreconf: configure.ac: tracing
configure.ac: warning: AM_GNU_GETTEXT is used, but not AM_GNU_GETTEXT_VERSION or AM_GNU_GETTEXT_REQUIRE_VERSION
autoreconf: running: libtoolize --copy --force
Can't exec "libtoolize": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 293.
autoreconf: error: libtoolize failed with exit status: 2

configure: WARNING: cannot find uuid via pkg-config or in the standard locations
configure: error: in `/1/zfs-2.1.12':
configure: error: *** libuuid-devel package required

Best way install zfs(with deduplication) via tdnf :-) but now it's absent :-(

I want deduplication on the fs level and zfs is more preferable for this...

**Comment by dcasota** [comment]
Hi,

gettext is an installable package using `tdnf install gettext`. However often it is easier to install the build-essential package with `tdnf install build-essential` because it includes compiler-helper packages as well.

Compile of the zfs package seems to work.
Could you verify with your configuration?

Test environment specification:
- Workstation 17, provisioned Ph 5.0 vm from photon-hw15-5.0-dde71ec57.x86_64.ova
- settings:
   - Upgrade this virtual machine: workstation 17.x (alter this virtual machine)
   - Floppy removed
   - virtual machine partially encrypted, Trusted Platform Module added
   - vm started and password changed.
   - Used the following commands.
```
tdnf install -y build-essential linux-esx-devel tar curl curl-devel libtirpc-devel libgudev-devel openssl openssl-devel libgcrypt

curl -J -L -O https://github.com/openzfs/zfs/releases/download/zfs-2.1.12/zfs-2.1.12.tar.gz
tar xzvf zfs-2.1.12.tar.gz
cd zfs-2.1.12/
./configure
make

# enable zfs modules
./bin/zfs --version
modprobe -i -v zfs
./bin/zfs --version
```

Hope this helps.
-Daniel

**Comment by gorec2005** [comment]
Big thank you Daniel!
mo
My environment specification:
esxi 6.7u3, provisioned Ph 5.0 vm from photon-hw15-5.0-dde71ec57.x86_64.ova

and your's receipt work like a charm for me!

**Comment by gorec2005** [comment]
Second trouble :-)
zfs on Ph 5.0 work ok, but how i can enable it's rescan and automount pools after reboot?

**Comment by dcasota** [comment]
Hi @gorec2005,

Unfortunately I'm not experienced enough with zfs services, and mounting, monitoring and troubleshooting zpools.

Accordingly to https://openzfs.github.io/openzfs-docs, it seems necessary to separate different scenarios, at least
A. Photon OS root on ZFS with secure boot (not supported)
B. Photon OS root on ZFS maintenance (system recovery configuration)
C. Photon OS' systemd related zfs-mount-generator configuration

Assuming you mean scenario C). Hopefully a member of the Photon OS team sees this second trouble and can add a curated answer.

Meanwhile I leave the notes below. Hope this helps.
-Daniel

---  

1. Having added two disks /dev/sdb and /dev/sdc, create a first zpool.  
```console
POOLNAME=newpool
/sbin/modprobe zfs
./bin/zpool create $POOLNAME mirror /dev/sdb /dev/sdc -f
```
List zpools.
```
./bin/zpool list
NAME      SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
newpool   960M   100K   960M        -         -     0%     0%  1.00x    ONLINE  -
```

2. set mountpoint
```console
./bin/zfs set mountpoint=/zfs $POOLNAME
```
show mountpoint.  
```
df /zfs

Filesystem     1K-blocks  Used Available Use% Mounted on
newpool           851968   128    851840   1% /zfs
```

3. Accordingly to [this source](https://wiki.archlinux.org/title/ZFS#General), ensure automatic start for a few zfs services.  
```console
systemctl enable zfs-import-cache.service
systemctl enable zfs.target
systemctl enable zfs-import.target
systemctl start zfs-import-cache.service
systemctl start zfs.target
systemctl start zfs-import.target
```
You can list the zfs services with `systemctl list-unit-files | grep zfs-`.  


4. zfs-import-cache needs a cache file per zpool.  
```console
mkdir -p /etc/zfs
./bin/zpool set cachefile=/etc/zfs/zpool.cache $POOLNAME
```

5. There seems to be an OpenZFS issue with /var dataset. Use zfs-mount-generator instead of zfs-mount.

docs reference: https://openzfs.github.io/openzfs-docs/man/8/zfs-mount-generator.8.html?highlight=zfs%20mount%20generator

```console
# systemctl stop zfs-mount.service
# systemctl disable zfs-mount.service
mkdir -p /etc/zfs/zfs-list.cache
ln -s /usr/lib/zfs/zed.d/history_event-zfs-list-cacher.sh /etc/zfs/zed.d
touch /etc/zfs/zfs-list.cache/$POOLNAME
systemctl enable zfs-zed.service
systemctl start zfs-zed.service
./bin/zfs set canmount=off $POOLNAME
```
```
# check content of /etc/zfs/zfs-list.cache/$POOLNAME, and run ./bin/zfs set canmount=on $POOLNAME
```
The recognition of the first zpool didn't work.
After a reboot, dmesg shows that zfs-mount-generator configuration wasn't applied successfully.
```
...
[    2.151140] systemd[1]: Detected virtualization vmware.
[    2.151144] systemd[1]: Detected architecture x86-64.
[    2.344086] (sd-execu[352]: /usr/lib/systemd/system-generators/zfs-mount-generator failed with exit status 127.
[    2.387500] systemd[1]: /usr/lib/systemd/system/dbus.socket:5: ListenStream= references a path below legacy directory /var/run/, updating /var/run/dbus/system_bus_socket → /run/dbus/system_bus_socket; please update the unit file accor
dingly.
...
```

**Comment by gorec2005** [comment]
Hi!
Thank you!
I made it work after reboot:

1.
root@photon [ / ]# systemctl list-unit-files | grep zfs
zfs-import-cache.service                                                      enabled         enabled
zfs-import-scan.service                                                       enabled         enabled
zfs-import.service                                                            masked          enabled
zfs-load-key.service                                                          masked          enabled
zfs-mount.service                                                             enabled         enabled
zfs-scrub@.service                                                            static          -
zfs-share.service                                                             enabled         enabled
zfs-volume-wait.service                                                       enabled         enabled
zfs-zed.service                                                               enabled         enabled
zfs-import.target                                                             enabled         enabled
zfs-volumes.target                                                            enabled         enabled
zfs.target                                                                    enabled         enabled
zfs-scrub-monthly@.timer                                                      disabled        enabled
zfs-scrub-weekly@.timer                                                       disabled        enabled


2. And make symlink  /etc/zfs -> /usr/local/etc/zfs (for correct reading zpool.cache by service)
root@photon [ / ]# zpool list
NAME   SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
fs  99.5G   707M  98.8G        -         -     0%     0%  7.42x    ONLINE  -

and all work correct after reboot!
and deduplication really COOL thing!
