### ISSUE TITLE
Unable to override DNS servers from DHCP

### ISSUE THREAD

**Issue by felixtech-msp** [vmware/photon#1494]
### Describe the bug

In Photon 5.0 it's impossible to make the system use manually specified DNS servers. It ignores the configuration and takes the DHCP received nameserver anyways.

### Reproduction steps

1. Set `/etc/systemd/network/10-static-en.network` to this content:
```
[Match]
Name=eth0

[Network]
DHCP=ipv4
DNS=192.168.1.2
DNS=192.168.1.3
IPv6AcceptRA=no

[DHCPv4]
UseDNS=false
```

2. `systemctl restart systemd-networkd`
3. `systemctl restart systemd-resolved`
4. `resolvectl status` still shows the DNS server received from DHCP

### Expected behavior

System should do what is configured and not ignore configuration and do whatever it wants anyways.

**Comment by dcasota** [comment]
Hi,

to disable adding the dns from dhcpv4 you could start with
```
[Match]
Name=eth0

[Network]
DHCP=ipv4
DNS=

[DHCPv4]
UseDNS=false
```
With respect to https://www.freedesktop.org/software/systemd/man/systemd.network.html#UseDNS= , `DNS=` disables the DNS servers received from the dhcp server. 

Afaik `/etc/dhcp/dhclient.conf` contains configuration information for dhclient, also for dns servers. I haven't tried it out, but there is an option `prepend domain-name-servers` which might help for your scenario described.

If `systemd-resolved` isn't needed at all because of a dns server of your own, disable/stop/mask might be necessary to get the result wanted.

**Comment by oliverkurth** [comment]
@ssahani

**Comment by ssahani** [comment]
what is the status of eth0
```
networkctl status eth0
```

**Comment by felixtech-msp** [comment]
@ssahani The interface status showed the following:
```
Network File: /etc/systemd/network/50-dhcp-en.network
```

So basically even though there is `10-static-en.network` with a specific match it doesn't use it and instead takes the generic `50-dhcp-en.network`.

After a change of owner and change of rights of the config file it now works.

Old status:
```
393717 4 -rw-r----- 1 root            root             114 Jul 17 11:25 10-static-en.network
393534 4 -rw-rw---- 1 systemd-network systemd-network   54 Jul 17 09:37 50-dhcp-en.network
394219 4 -rw-r--r-- 1 root            root              77 Jun 29 20:38 99-dhcp-en.network
```

New status:
```
393717 4 -rw-rw---- 1 systemd-network systemd-network  114 Jul 17 11:25 10-static-en.network
393534 4 -rw-rw---- 1 systemd-network systemd-network   54 Jul 17 09:37 50-dhcp-en.network
394219 4 -rw-r--r-- 1 root            root              77 Jun 29 20:38 99-dhcp-en.network
```

Should be put into the documentation: https://vmware.github.io/photon/docs-v5/administration-guide/managing-network-configuration/adding-a-dns-server/

**Comment by ssahani** [comment]
It's already documented https://vmware.github.io/photon/docs-v5/administration-guide/managing-network-configuration/configuring-network-interfaces/
