### ISSUE TITLE
TDNF Ansible Module not working

### ISSUE THREAD

**Issue by felixtech-msp** [vmware/photon#1508]
### Describe the bug

The Ansible module for TDNF found under https://github.com/vmware/photon/blob/master/SPECS/ansible/tdnf.py isn't working.

The error message is as following:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable

Traceback (most recent call last):
 File \"/home/awx/.ansible/tmp/ansible-tmp-1696251955.61725-318-195202107349459/AnsiballZ_tdnf.py\", line 107, in  _ansiballz_main()
 File \"/home/awx/.ansible/tmp/ansible-tmp-1696251955.61725-318-195202107349459/AnsiballZ_tdnf.py\", line 99, in _ansiballz_main
 invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
 File \"/home/awx/.ansible/tmp/ansible-tmp-1696251955.61725-318-195202107349459/AnsiballZ_tdnf.py\", line 47, in invoke_module
 runpy.run_module(mod_name='ansible.modules.tdnf', init_globals=dict(_module_fqn='ansible.modules.tdnf', _modlib_path=modlib_path),
 File \"\", line 226, in run_module
 File \"\", line 98, in _run_module_code
 File \"\", line 88, in _run_code
 File \"/tmp/ansible_tdnf_payload_fsw168bt/ansible_tdnf_payload.zip/ansible/modules/tdnf.py\", line 368, in 
 File \"/tmp/ansible_tdnf_payload_fsw168bt/ansible_tdnf_payload.zip/ansible/modules/tdnf.py\", line 332, in main
 File \"/tmp/ansible_tdnf_payload_fsw168bt/ansible_tdnf_payload.zip/ansible/modules/tdnf.py\", line 292, in convert_to_list
TypeError: 'NoneType' object is not iterable
```

The task to run was:
```
- name: update installed packages
  tdnf:
    update_cache: yes
    upgrade: yes
```

### Reproduction steps

1. Create Ansible role and put module file under library folder.
2. Run above described Ansible task on a Photon OS 5.0 machine.
3. Observe the error.

### Expected behavior

Run TDNF tasks as intended ans described by documentation.

### Additional context

Ansible Version 2.13.6
Python Version 3.10.11

**Comment by snapshotleisure** [comment]
Hi, this is the same issue for me with the same configuration

**Comment by snapshotleisure** [comment]
Hi, 
I actually have a fix for this, the bug is actually in the function called convert_to_list at line 288. It is not doing a check for NoneType.

You can find the files in the following locations:
- /usr/lib/python3.11/site-packages/ansible/modules/tdnf.py
- /usr/lib64/python3.11/site-packages/ansible/modules/tdnf.py

You will need to update the function like below with the None check:
def convert_to_list(input_list):
    """Convert nested list into flat list"""
    flat_list = []

    if input_list is not None:
      for sublist in input_list:
          if not isinstance(sublist, list):
              flat_list.append(sublist)
              continue
          if sublist is not None:
            for item in sublist:
                flat_list.append(item)

    return flat_list

Then you need to run the command below to recompile it:
python -c "import py_compile;py_compile.compile('/usr/lib/python3.11/site-packages/ansible/modules/tdnf.py');py_compile.compile('/usr/lib64/python3.11/site-packages/ansible/modules/tdnf.py');"

After that it should work.

Unfortunately I'm not really good with git, so don't know how to request pull request to fix up the code, but hope this helps people and the devs will fix up the function

**Comment by snapshotleisure** [comment]
Ok tried to do a pull request, will see if it works
