### ISSUE TITLE
Cant get wlan working with realtek b852 device

### ISSUE THREAD

**Issue by mnivoliez** [vmware/photon#1549]
### Describe the bug

The wifi chip is not detected as such
```
# lspci -nn
...
02:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 15)
03:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. Device [10ec:b852]
...
```
```
# networkctl
IDX LINK TYPE     OPERATIONAL SETUP
  1 lo   loopback carrier     unmanaged
  2 eth0 ether    routable    configured

2 links listed.

```

### Reproduction steps

1. Install Photon Os
2. Try to connect wifi following documentation

### Expected behavior

The driver seems not to be included. 
I would have expected to have it.

### Additional context

I tried to install https://github.com/lwfinger/rtw89 to no avail.

**Comment by dcasota** [comment]
Hi, 

fyi In https://communities.vmware.com/t5/Photon-OS-Discussions/How-to-install-and-configure-Wi-Fi-drivers-in-Photon-OS/m-p/2951542/highlight/true#M375 there was a similar discussion a while ago. lwfinger/rtw89 was used there, too.

which host system and Photon OS release?

**Comment by mnivoliez** [comment]
I am running an acemagic amr5 and photon 5.0
I followed the link you send, same result.

**Comment by dcasota** [comment]
As suggestion, can you compile the source mentioned in [https://github.com/HRex39/rtl8852be?tab=readme-ov-file#buildfor-kernel--518 ?](https://github.com/HRex39/rtl8852be?tab=readme-ov-file#buildfor-kernel--518-1) ? That one from  branch dev (`git clone https://github.com/HRex39/rtl8852be.git -b dev`).

**Comment by mnivoliez** [comment]
Sadly it does not even compile (the kernel may be too advanced)

**Comment by dcasota** [comment]
ok. Will start tomorrow analyzing and will report back.

**Comment by mnivoliez** [comment]
Sadly it does not even compile (the kernel may be too advanced).
I manage to got the chip recognize by following this:
https://github.com/lwfinger/rtw89/issues/259#issuecomment-1646842257

**Comment by mnivoliez** [comment]
Still can't manage to connect though.

**Comment by dcasota** [comment]
First, baremetal support usually is out of scope of Photon OS. See answer in https://github.com/vmware/photon/issues/1510#issuecomment-1862086810.

If the Linux packages of Photon OS 3.0/4.0/5.0 do not include the firmware for a nic, you have to add it for your own.
Unfortunately I do not have a device with [10ec:b852] to test it out. So the following recipe is theory only. Please, test it carefully.
```
cd $HOME
tdnf install -y git usbutils pciutils wpa_supplicant git make build-essential linux-api-headers linux-firmware dkms dracut

# generic flavor
tdnf install -y linux-devel

git clone git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git --depth 1
# Realtek has bluetooth, lan and wifi firmware in linux-firmware subtree. Copying rtw89 files to /lib/firmware
cp $HOME/linux-firmware/rtw89/rt*.bin /lib/firmware

mkinitrd
# reboot or restart daemon/services

# compile the software driver
git clone https://github.com/lwfinger/rtw89
cd ./rtw89
make
make install
modprobe -v rtw_8852b
lsmod | grep 8852
```
The above should work. However, if it doesn't work, then there are additional steps necessary.

Accordingly to https://github.com/lwfinger/rtw89/issues/275#issuecomment-1784155449 you may have to disable conflicting options. This is done by adding in `/etc/modprobe.d/rtw8852b.conf` the configuration needed.

I'm definitely not sure if the following setting works.
```
cat <<EOF >/etc/modprobe.d/rtw8852b.conf
options rtw89_pci disable_aspm_l1=y disable_aspm_l1ss=y
options rtw89pci disable_aspm_l1=y disable_aspm_l1ss=y
options rtw89_core disable_ps_mode=y
options rtw89core disable_ps_mode=y
EOF
```

Replacing sources in `$HOME/rtw89` shouldn't be necessary because the [sources in ](https://github.com/lwfinger/rtw89/issues/259#issuecomment-1646842257) has been closed. Nevertheless, here a snippet to downloads the latest drivers.
```
cd $HOME
git init
git remote add origin https://github.com/torvalds/linux.git
git config core.sparsecheckout true
echo "drivers/net/wireless/realtek" > .git/info/sparse-checkout
git pull --depth=1 origin master
git checkout FETCH_HEAD

ls $HOME/drivers/net/wireless/realtek/rtw89
```

Hope it helps,

**Comment by mnivoliez** [comment]
Thanks!
