### ISSUE TITLE
No swap prartition.

### ISSUE THREAD

**Issue by netw0rm** [vmware/photon#211]
I want to know how to set a swap prartition,
why don't add it to installing.

**Comment by mbassiouny** [comment]
Thanks for the comment, currently we do not have a way to set it during the installation. We may add it as part of the quite unattended installation, and ability to specify that in kickstart config file. Will keep you updated.

**Comment by mattolenik** [comment]
I think a swap file instead of partition would be fine if that makes implementation easier. Not having swap space is critical IMO. It means any Photon VM being taxed with compute resources is likely to fall over as soon as memory runs out, rather than just slowing down. I've already hit this building a Photon-based Vagrant VM.

**Comment by ppadmavilasom** [comment]
we will work on adding a swap partition.

**Comment by sharathjg** [comment]
the installer change here : https://github.com/vmware/photon/commit/72832a72f44f8f004192664673fcc391edfb5275 allows creating a swap parition.
