### ISSUE TITLE
How to change keyboard layout map from qwerty to azerty

### ISSUE THREAD

**Issue by sunsimo** [vmware/photon#44]
Hello,

please add the possibility to chose keyboard layout in post-installation mode

thanks

**Comment by sunsimo** [comment]
after searching at prompt tape: #  localectl set-keymap azerty

but it will be nice to setup keyboard layout during installer as a feature to be added

thanks.

**Comment by David-EU** [comment]
2018 in a few days and the problem still exist. It is worth now that Photon is ridig as hell when setting the password, can't set a "simple" password to avoid languages typos and change it later, you need to make it complex with signs, capitals, letters+numbers etc... but you don't even know what you type in the box since the keyboard language doesn't match, I can do the translation with the letters but the rest... :x
Please be more permissive, we are mostly all it specialist and don't need to be educated to know when to type/change a password and make it complex. Note like end-users that want "123" as password so please let us control our systems in the way we want.
