### ISSUE TITLE
Need OVA for full version of photon

### ISSUE THREAD

**Issue by rdachere** [vmware/photon#517]
Apparently there is a full version. What I downloaded is a minimal install and doesn't have a whole host of packages.

**Comment by suezzelur** [comment]
Please modify the common/data/packages_minimal_ova.json to include the necessary packages you need and build the ova manually using `sudo make cloud-image IMG_NAME=ova` after going through  https://github.com/vmware/photon/blob/master/docs/cloud-images.md#ova
Currently there are no plans to release a full ova due to the image size constraints.
