### ISSUE TITLE
Docker containers losing name resolution

### ISSUE THREAD

**Issue by deviantony** [vmware/photon#555]
For some reasons, some of my containers lose name resolution (unable to ping google.com for example).

Now, this happens only to some of the containers on my Docker host and not all of them.

I did specify my DNS server using the DNS variable in both `/etc/systemd/network/10-static-en.network` and `/etc/systemd/resolv.conf` files.

Note, it seems that the content of the file `/etc/resolv.conf` changes each time I start a container... the content of the file is kindof similar (with an extra search-domain specified as `Domains` in the `10-static-en.network` file and not in the `resolv.conf` file). Like if it was switching, one time using the configuration from `/etc/systemd/network/10-static-en.network` and the next time from `/etc/systemd/resolv.conf`. This is really strange.

Is this a known issue?

**Comment by vinaykul** [comment]
We have not seen this issue. Could you please provide repro steps?

**Comment by deviantony** [comment]
I'll try to give you a reproduction setup. I have a simple compose setup where one of my containers lose name resolution after some time.

I'll create a small repro repository for the compose setup.

**Comment by vinaykul** [comment]
If you are specifying static DNS entries /etc/systemd/resolved.conf in a DHCP environment, please set UseDNS=false in your 10-static-en.network file so that systemd uses your static entry as opposed to switching to the DHCP DNS server entry. Please see UseDNS and UseDomains in https://www.freedesktop.org/software/systemd/man/systemd.network.html

AFAIK, docker copies the host /etc/resolv.conf that systemd baked, and brings it into the container /etc/resolv.conf and removes any IPv6 DNS server entries. If the DNS servers are reachable from the host, they should be reachable from the container.

**Comment by sharathjg** [comment]
closing this as there doesnt seem to be an update on this. If you still hit this issue, can you reopen this?
