### ISSUE TITLE
Addition of packages lz4 and lz4c?

### ISSUE THREAD

**Issue by michaelpq** [vmware/photon#566]
There is nothing for lz4 and particularly lz4c. Perhaps an addition of those packages could be considered. lz4 is cheap in CPU and compresses well, in terms of CPU it is better than gzip and xz for example.

**Comment by suezzelur** [comment]
Fixed by commit https://github.com/vmware/photon/commit/55a884bf4f9b7c1bc1f47a768a063f40c8cae754 anda available in the photon_dev_x86_64 repo. Refer to [admin guide](https://github.com/vmware/photon/blob/master/docs/photon-admin-guide.md#adding-the-dev-repository-to-get-new-packages-from-the-github-dev-branch) to add the dev repo.

**Comment by michaelpq** [comment]
Thanks!
