### ISSUE TITLE
How to add a default gateway in Photon ?

### ISSUE THREAD

**Issue by jolypas** [vmware/photon#584]
hello

despite I put a gateway "ip_gw" into  /etc/systemd/network/10-eth0.network
 I have to do manually at each boot

route add _ip_gw_ dev eth0
route add default gw _ip_gw_

where to add this at boot level for photon ?

thanks

**Comment by vinaykul** [comment]
The default gateway is usually assigned by the DHCP server.

Since you are looking to have a persistent default gateway configuration, please try setting it in 10-eth0.network file by specifying Gateway=<Gateway IP address> in the [Network] section of the file. 

OTOH, if you were looking to add a route (as opposed to a default gateway), you can add a [Route] section to the configuration file. Please review https://www.freedesktop.org/software/systemd/man/systemd.network.html
