### ISSUE TITLE
Missing PayloadIsLzma feature in rpmlib

### ISSUE THREAD

**Issue by McCzarny** [vmware/photon#589]
Hello,
I am working with VMware VCenter appliances and packages built in 6.0 (opensuse based) does not work in 6.5 (PhotonOS), because rpmlib does not have feature PayloadIsLzma. Will it be possible to introduce this feature in PhotonOS? It is missing because of the old rpm package or to make OS smaller?

Some additional info:
Package installation fails with message:

```
error: Failed dependencies:
'rpmlib(PayloadIsLzma) <= 4.4.2-1 is needed'
```

Available rpmlib features:
```
Features supported by rpmlib:
    rpmlib(BuiltinLuaScripts) = 4.2.2-1
    rpmlib(CompressedFileNames) = 3.0.4-1
    rpmlib(ConcurrentAccess) = 4.1-1
    rpmlib(ExplicitPackageProvide) = 4.0-1
    rpmlib(FileCaps) = 4.6.1-1
    rpmlib(FileDigests) = 4.6.0-1
    rpmlib(HeaderLoadSortsTags) = 4.0.1-1
    rpmlib(PartialHardlinkSets) = 4.0.4-1
    rpmlib(PayloadFilesHavePrefix) = 4.0-1
    rpmlib(PayloadIsBzip2) = 3.0.5-1
    rpmlib(ScriptletExpansion) = 4.9.0-1
    rpmlib(ScriptletInterpreterArgs) = 4.0.3-1
    rpmlib(TildeInVersions) = 4.10.0-1
    rpmlib(VersionedDependencies) = 3.0.3-1
```

Thanks for help!

**Comment by kganugapati** [comment]
Sharath priyesh please investigate this

Sent from my iPhone

On Jan 9, 2017, at 12:44 AM, McCzarny <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
I am working with VMware VCenter appliances and packages built in 6.0 (opensuse based) does not work in 6.5 (PhotonOS), because rpmlib does not have feature PayloadIsLzma. Will it be possible to introduce this feature in PhotonOS? It is missing because of the old rpm package or to make OS smaller?

Some additional info:
Package installation fails with message:

error: Failed dependencies:
'rpmlib(PayloadIsLzma) <= 4.4.2-1 is needed'


Available rpmlib features:

Features supported by rpmlib:
    rpmlib(BuiltinLuaScripts) = 4.2.2-1
    rpmlib(CompressedFileNames) = 3.0.4-1
    rpmlib(ConcurrentAccess) = 4.1-1
    rpmlib(ExplicitPackageProvide) = 4.0-1
    rpmlib(FileCaps) = 4.6.1-1
    rpmlib(FileDigests) = 4.6.0-1
    rpmlib(HeaderLoadSortsTags) = 4.0.1-1
    rpmlib(PartialHardlinkSets) = 4.0.4-1
    rpmlib(PayloadFilesHavePrefix) = 4.0-1
    rpmlib(PayloadIsBzip2) = 3.0.5-1
    rpmlib(ScriptletExpansion) = 4.9.0-1
    rpmlib(ScriptletInterpreterArgs) = 4.0.3-1
    rpmlib(TildeInVersions) = 4.10.0-1
    rpmlib(VersionedDependencies) = 3.0.3-1


Thanks for help!

-

**Comment by ppadmavilasom** [comment]
@McCzarny it's best to install packages built with photon's toolchain. is there a way you can build the packages in question from sources or is that not an option?

**Comment by ppadmavilasom** [comment]
@McCzarny this is submitted to photon dev: https://github.com/vmware/photon/commit/fdba7f85c130696766c44abb61434e94c7d9dc9c

dev repo is at https://bintray.com/vmware/photon_dev_x86_64

HTH
