### ISSUE TITLE
Where to place restore-iptables script

### ISSUE THREAD

**Issue by scriptjs** [vmware/photon#641]
Where are folks placing their restore-iptables script. I don't see a service unit for rc.local type compatibility unless I make it.

**Comment by ppadmavilasom** [comment]
add your iptables command to /etc/systemd/scripts/iptables

**Comment by scriptjs** [comment]
I've appended it there put it there but makes me think there could be an rc.local in /etc and an rc-local.service added at /etc/systemd/system.

**Comment by ppadmavilasom** [comment]
you can do this in a per service basis - this might be best. If that doesnt work, use the iptables script or modify it to fit your needs 

@alanjcastonguay said he uses something like this

I've been doing something like following `iptables-port-443-open.service` instead of disabling the firewall entirely. 
```[Unit]
Description=Create Iptables rule to allow inbound traffic to port 443
After=iptables.service
Requires=iptables.service

[Service]
Type=oneshot
ExecStart=/usr/sbin/iptables -A INPUT -p tcp --dport 443 -j ACCEPT
ExecStop=-/usr/sbin/iptables -D INPUT -p tcp --dport 443 -j ACCEPT
TimeoutSec=0
RemainAfterExit=yes

[Install]
WantedBy=iptables.service```

**Comment by alanjcastonguay** [comment]
I do use something like, that and find it works fairly well. Also means that the daemon that's planning on listening on port 443 can `Requires` this unit, and enables port-closure on daemon stop.

**Comment by scriptjs** [comment]
@alanjcastonguay I like this approach :) Thank you for sharing.

**Comment by ppadmavilasom** [comment]
@scriptjs i like @alanjcastonguay 's solution as well. there is not going to be a guideline from photon on how to do this as dev solutions vary and its hard to reach a consensus. we intend to leave the iptables script as a general hook if you need to use it so that a reboot will guarantee rules applied.
