### ISSUE TITLE
Package requests: screen htop

### ISSUE THREAD

**Issue by Neo-Desktop** [vmware/photon#650]
If possible, it would be nice to have packages of [GNU Screen](https://www.gnu.org/software/screen/) and [htop](https://github.com/hishamhm/htop) for Photon

Thanks!

**Comment by YustasSwamp** [comment]
Photon OS 2.0 will have `tmux`. Which might be used as `screen` replacement

**Comment by YustasSwamp** [comment]
We are trying to keep Photon OS as small as possible and to avoid different alternatives with the same functionality.
Alternative to screen is tmux
Alternative to htop are procps + coreutils

Thanks!

**Comment by rainabba** [comment]
I understand the image-size concern, but in my experience, htop is the modern standard for resource monitoring. Not including it by default makes sense, but not providing the package is mind-boggling for me and now I'm going to have to try and find or build a binary instead of working on my app (which IS the point of Photon right)? Of course, I could always just kill my ram further by using the vSphere web interface and digging through 3 levels of menus to get the info I'd get with only `htop` and a few seconds of watching.

**Comment by densanki** [comment]
The shit hits the fan, WHY...
