### ISSUE TITLE
How to set root password with cloud-config?

### ISSUE THREAD

**Issue by ipetkov7** [vmware/photon#659]
Is there a way to set/change the root user password with cloud-config, when deploying the Photon OVA?

**Comment by kaushik229** [comment]
Yes, you can use cloud-init to configure password. Please provide the salted password hash in configuration. You can generate one using 
openssl or mkpasswd

Example,

#cloud-config

users:
    - name: root
      lock-passwd: false
      passwd: $1$SaltSalt$YhgRYajLPrYevs14poKBQ0

The above password is generated for plain-text password "secret"

root@localBoxISO [ ~ ]# openssl passwd -1 -salt SaltSalt secret
$1$SaltSalt$YhgRYajLPrYevs14poKBQ0
root@localBoxISO [ ~ ]#

**Comment by tsimchev** [comment]
@kaushik229 this is not working for photon 3.0

```
users:
          - name: root
            lock-passwd: false
            passwd: VMwarensbu_2!
```

<img width="1311" alt="Screen Shot 2020-06-28 at 6 11 08 PM" src="https://user-images.githubusercontent.com/13386601/85951291-ee113b00-b96a-11ea-918e-fb2773c224a7.png">

**Comment by sshedi** [comment]
Hi @tsimchev,

You should use hashed password. Below info is from cloud-init documentation.

passwd: The hash -- not the password itself -- of the password you want
#           to use for this user. You can generate a safe hash via:
#               mkpasswd --method=SHA-512 --rounds=4096
#           (the above command would create from stdin an SHA-512 password hash
#           with 4096 salt rounds)

For more info: https://cloudinit.readthedocs.io/en/latest/topics/examples.html

--
Shedi

**Comment by tsimchev** [comment]
Thanks @sshedi, I missed that. It works now.

**Comment by ambis** [comment]
Hi,

Since this is the first google hit on resetting root password, I tought I'd share my findings.

Above, the `lock-passwd` has a typo. The proper key is `lock_passwd` with an underscore.

Also instead of `password` one should use `hashed_passwd` for existing users (like root). See the first "Note:" [here](https://cloudinit.readthedocs.io/en/latest/topics/examples.html).

So ended up using:
```
users:
  - name: root
    lock_passwd: false
    hashed_passwd: '$6$RGHkEd9zPlz84lC$ZeMhzKPE8pgzYTtWrAG0....etc....'
```

Works like a charm!

cloud-init 20.2 on debian10

Also btw, the `mkpasswd` tool is installed by installing the `whois` package.

**Comment by kbragdon85** [comment]
Ok guys. I am confused and I apologize in advance if I am missing something... because I definitely am missing something and having a hell of a time with this.
Info:
RHEL 8.4
VMware VRealize Automation: On-Prem using a Cloud-agnostic blueprint

So... for the Hashed password... Does the VM you are creating need to create the Hash or can you just supply a Hash? I assume that the Hash should be the same no matter what but I have tried to supply a Hash (SHA 512) but the Hash doesn't get decoded correctly/the VM doesn't accept the Hash
I am using Vrealize Automation, so I have inputs... I am not even sure if inputs would work here... So...
Would I need to generate that Hash on the VM and update the configuration file that cloud-init is using for the password?
Or
Would/Can I just supply the Hash via the cloud-init/Cloud-config as an input?


Example of what I am supplying:
      cloudConfig:
        users:
          - name: '${input.userID}'
            lock_passwd: false
            no_user_group: true
            groups: wheel
	    hashed_passwd: '${input.UsrPassword}'
        ssh_pwauth: true
        preserve_hostname: false
        hostname: '${input.vmname}'

**Comment by sshedi** [comment]
Did you go through https://cloudinit.readthedocs.io/en/latest/topics/examples.html?

```
#   passwd: The hash -- not the password itself -- of the password you want
#           to use for this user. You can generate a safe hash via:
#               mkpasswd --method=SHA-512 --rounds=4096
#           (the above command would create from stdin an SHA-512 password hash
#           with 4096 salt rounds)
```

On Photon, you can do it using:
```
tdnf install -y toybox
mkpasswd -m sha512 test_passwd -S "11223344"
```
And use the resultant hash.

**Comment by shock0572** [comment]
can packer compute a hash of a password?
