### ISSUE TITLE
Request for MariaDB with Galera Cluster

### ISSUE THREAD

**Issue by machenbach** [vmware/photon#672]
The current mariadb package doesn't seem to have Galera Cluster in it.  We require this for our use.

**Comment by ppadmavilasom** [comment]
are you planning to use this with photon 1.0?

**Comment by machenbach** [comment]
Yes.

**Comment by machenbach** [comment]
Is there any update on this request?

**Comment by xiaolin-vmware** [comment]
Enabled server, and Galera Cluster, in commit 51815e2df87e4dc1bf3d482d2d0a1422254312b0.

**Comment by charandas** [comment]
@dthaluru Before you close this for good, I wish to bring it to your attention that Galera is actually not working on Photon 2.0 in my experience. My versions are below:

```
mariadb-errmsg         x86_64      10.2.10-1.ph2  photon-updates   2.24M 2350568
mariadb-server         x86_64      10.2.10-1.ph2  photon-updates 129.49M 135781332
mariadb-server-galera  x86_64      10.2.10-1.ph2  photon-updates   5.69k 5829
```

My guess is, it is due to the missing `libgalera_smm.so` in the manifest/SPEC. The path to this file needs to be set as `wsrep_provider` before any kind of cluster can be established. The build procedure for this is in the [official docs](https://mariadb.com/kb/en/library/installating-galera-from-source/).

Could you please take a look, or let me know if you would prefer me to open this as a new issue?

**Comment by dthaluru** [comment]
@charandas Can you please open a new issue? Thanks!!!
