### ISSUE TITLE
Documentation update: cloud-init

### ISSUE THREAD

**Issue by linkages** [vmware/photon#703]
In Photo OS Administration guide here: https://github.com/vmware/photon/blob/master/docs/photon-admin-guide.md

In the last paragraph of the "Cloud-init for Photon OS" section it reads:

"The following sections demonstrate how to use cloud-init to customize a stand-alone Photon OS machine, instantiate a Photon OS machine in the Amazon EC2 cloud, and deploy a virtual machine running Photon OS in vSphere."

There are further sections that cover both stand-alone and EC2 but the section for using cloud-init on vSphere is missing.

Can some directions be created for running/installing Photon OS on vSphere using cloud-init.

Thanks.

**Comment by jnovack** [comment]
Good luck son. That's because there isn't any direct method.

[Cloud-Init does not support vSphere as a source.](http://cloudinit.readthedocs.io/en/latest/topics/datasources.html#datasource-documentation)

Sure, if you want to mess around with OVF, you can. That would require you [modifying an OVF file](https://searchvmware.techtarget.com/tip/How-to-create-a-VMware-OVF-virtual-appliance), [then compressing the OVF+VMDK into a OVA](https://www.vmware.com/support/developer/ovf/ovf10/ovftool_10_userguide.pdf). But the general consensus is to ISO it. 

Action Suggestion: vSphere section should be removed.  Not Photon's fault.

**Comment by stuclem** [comment]
For investigation in the next release.

**Comment by mikeroySoft** [comment]
cleaning up stale doc issues
