### ISSUE TITLE
tdnf is not installed by default in Photon OS 3.0 Revision 2 Binaries

### ISSUE THREAD

**Issue by rui-su-bnet** [vmware/photon#964]
Not sure if this is default or not, i noticed that tdnf is not installed by default in Photon OS 3.0 Revision 2 Binaries.  
Reproducing the problem 
- Install download the photon-3.0-58f9c74.iso on virtual box 
- minimum and OStree version
- post install 
```
root@photon-74706d236902 [ /etc/yum.repos.d ]# cat /etc/photon-release
VMware Photon OS 3.0
PHOTON_BUILD_NUMBER=49d932d
root@photon-74706d236902 [ /etc/yum.repos.d ]# tdnf
-bash: tdnf: command not found
root@photon-74706d236902 [ /etc/yum.repos.d ]# tdnf -y install gcc
-bash: tdnf: command not found
root@photon-74706d236902 [ /etc/yum.repos.d ]# find /sysroot/ -name "tdnf"
root@photon-74706d236902 [ /etc/yum.repos.d ]# find /sysroot/ -name "*tdnf*"
root@photon-74706d236902 [ /etc/yum.repos.d ]#
```

**Comment by jaankit** [comment]
Ostree flavour of Photon has its own package manager "rpm-ostree". Photon Ostree Atomic OS  does not include tdnf or any other package manager because updates and rollbacks are performed transactionally with the "rpm-ostree” command.
If you want to install any package, you can use "rpm-ostree install pkg-name". Package will be installed as layered package.
Since, Ostree is an Atomic OS. So it maintains the state of each upgrade/installation (rpm-ostree status -v).
Please refer https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/Photon-RPM-OSTree-a-simple-guide.html

And "Minimal" flavour of Photon has tdnf package as package manager.

**Comment by rui-su-bnet** [comment]
@jaankit  thank you very much i actually made a mistake.  tdnf is included in minimum.  Just did an reinstall.
